# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: DONGWAN KANG
title: Quantity Surveyor + Developer
email: dongwan.kng@gmail.com    
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: kangdongwan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/pf1.jpeg
about_content: | # this will include new lines to allow paragraphs
   My name is DONGWAN. I am a Quantity Surveyor (QS) with over 10 years of experience specializing in <mark>Procurement</mark> and 
   <mark>Cost Planning & Control</mark> in the Construction Industry.
   I am currently working for [_JUNGLIM CM Co., Ltd.,_](http://www.junglim.com/?lang=en) 
   as a researcher and developer for planning and development of <mark>CM</mark>(Construction Management) System to enhance the estimated construction cost and schedule in connection with BIM.
   In order to specialize my career as QS, I have completed <mark>FIDIC</mark> and <mark>QS</mark> courses, 
   including Contract Administration, FIDIC modules, Procurement, etc.
    
   The things that I am currently interested in are:   
   + Analyzing the Data including Construction Cost, BOQ, etc., and developing the program using <mark>VBA</mark>, <mark>Python</mark>, and <mark>Power BI</mark>
   + I expect to expand the scope of language using <mark>Python</mark> for Deep Learning or Machine Learning

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Researcher & Developer 
        sub_title: CM Technical Research Institute
        caption: JUNGLIM CM Co., Ltd. (Current ~ )
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          As a Researcher and Deleloper, I am currently participated in the projects for developing the system to be used at JUNGLIM CM.
          + Working on Planning and Developing an Integrated Document Management System (IDMS) to be used at JUNGLIM CM
          + Working on Planning and Devloping a estimation model (Quantity Take-off) for structural work using BIM extracted data

      - layout: left
        title: Construction Manager 
        sub_title: CM Team for Latin America Region of KOICA
        caption: JUNGLIM Architecture Co., Ltd. 
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          As a Resident Construction Manager who managed 5 construction projects in Dominican Republic (DR) and Guatemala, I had participated in the project on behalf of KOICA DR office. 
          In consideration of the characteristics and the local conditions of each project, all conditions for the project progress were prepared, and I have mainly worked as belows.   
          + Established the <mark>Bidding Strategies</mark> and <mark>Plan</mark> for the bidding process, including the evaluation, for construction and service 
          + Prepared the bidding documents, and proceeded with the bidding process for the selection of Construction Contractor and Supervisor, then proceeded with <mark>Contract Negotiations</mark> with preferred negotiators
          + Understood the reasons for failure in bidding through interviews with the local contractors and identified the status of qualified companies considering the progress of private contract
          + <mark>Contract Management</mark> (including variations for $140K, etc) and construction management of interim-payment, quality, and safety

      - layout: left
        title: Quantity Surveyor
        sub_title: Quantity Surveyor Team
        caption: JUNGLIM Architecture Co., Ltd.
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #link_text: Link Text
        #additional_links:
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #  - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #    icon: fab fa-github
        #    url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: | # this will include new lines to allow paragraphs
          As Quantity Surveyor, I had analyzed and established a database for estimating the Construction Cost in the design phase, 
          including correlation analysis using <mark>SPSS</mark> between Construction Cost and input of design outline,
          then I was developing a Model using Excel with <mark>VBA</mark> that estimates the Construction Cost.
          I also prepared and reviewed the Bill of Quantity and Cost Statements of the several design services in domestic,   
          + Estimating the Appropriate Construction Cost for the Remodeling of New Construction Projects in Design Phase, 
          + Controled and Planned the Construction Cost of the Design Works,
          + Evaluated the tender documents submitted by the Tendering Parties,
          Research and Development Project
          + Development of the Model for Estimating the Appropriciate Construction Period based on <mark>Case-Based Reasoning</mark> in Concept Design Phase,
          + Development of the Management Tool for Construction Cost per Room Unit in Design Phase using DATA extracted from <mark>BIM</mark>,

  - title: Employment
    layout: list
    content:
      - layout: right
        title: JUNGLIM CM Co., Ltd.
        sub_title: Director
        caption: Jan. 2023 - Present
        link: http://www.junglim.com
        description: | # this will include new lines to allow paragraphs

      - layout: right
        title: JUNGLIM Architecture Co., Ltd.
        sub_title: Director
        caption: Jan. 2010 - Dec. 2022
        link: http://www.junglim.com
        description: | # this will include new lines to allow paragraphs

  - title: Education
    layout: list
    content:
      - layout: left
        title: Quantity Surveyor (QS) Training Programme
        sub_title: Certified Programme of QS Training Programme 
        caption: May. 2014 - Oct. 2014
        description: | # this will include new lines to allow paragraphs
          I completed the various modules, including Construction Law and Dispute, Cost Planning and Control, Procurement and Tendering, Contract Practice, etc.
      - layout: left
        title: FIDIC-KENCA Accredited Training Programme
        sub_title: Certified Programme of FIDIC-KENCA Accredited Training 
        caption: May. 2012 - Oct. 2012
        description: | # this will include new lines to allow paragraphs
          I completed 10 Modules, including Contract Management and Administration, FIDIC Modules, Project Procurement, etc. 
      - layout: left
        title: University of Seoul
        sub_title: M.S. Construction Management 
        caption: Mar. 2008 - Feb. 2010
        description: | # this will include new lines to allow paragraphs
          I had performed the various projects such as <mark>VE</mark> (Value Engineering) in Construction and also participated in research project, 
          which is developed the Model for Estimating the Construction Cost and Building Management System funded by Ministry of Land, Transportation and Maritime.
          I published 1 paper in poster session, and 3 papers at conference.   
          + _Kang, D.W._, Ji, S.M., etc., Development of Cost Data Prototype based on Production Crew by Productivity Analysis of Form Work (Jan. 2012, [_Paper_](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001629968) in Korean),
          + _Kang, D.W._, Sim, J.G., etc., A Study on the Productivity Analysis of Superstructure Construction for Multi-Housing Projects Using Construction Simulation (Apr. 2010, [_Paper_](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001442687) in Korean),   
          + _Kang, D.W._, Moon H.S., etc., Development of a Simulation Model for the Productivity Analysis of Form Work in Multi-Family Housing Construction Projects (Nov. 2009, [_Paper_](https://scienceon.kisti.re.kr/srch/selectPORSrchArticle.do?cn=NPAP13265387) in Korean),   
          + Jin, R.Z., _Kang, D.W._, Sim, J.G, etc., A Study on the Life Cycle Cost of a Grating (May. 2009, ICCEM-ICCPM 2009, Poster Session)
      - layout: left
        title: Jeju National University 
        sub_title: B.S. Architectural Engineering #Construction Management
        caption: Mar. 2000 - Feb. 2008
        description: |

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
#
#      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
